name: LikeC4
description: LikeC4 GitHub Action
author: likec4

inputs:
  action:
    description: action to perform ("build"/"export"/"codegen")
    required: false
  export:
    description: export views ("png")
    required: false
  codegen:
    description: generate code
    required: false
  path:
    description: directory with likec4 sources
    required: false
  output:
    description: output directory/file
    required: false
  base:
    description: base url the app is being served from
    required: false
  likec4-version:
    description: 'likec4 version to use (default: bundled with action)'
    required: false

runs:
  using: docker
  image: docker://ghcr.io/likec4/actions:v1.48.0

branding:
  icon: image
  color: gray-dark