name: on-push-tag

on:
  push:
    tags:
      - "v*"

permissions:
  contents: write
  deployments: write
  packages: write
  actions: write      

jobs:

  build-docker:
    name: build docker for tag
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4  
        with:
          fetch-depth: 0
          fetch-tags: true

      - name: build package
        uses: elgohr/Publish-Docker-Github-Action@v5
        with:
          name: ${{ github.repository }}
          username: ${{ github.actor }}
          password: ${{ secrets.GITHUB_TOKEN }}
          registry: ghcr.io
          buildoptions: "--force-rm"
          tag_names: true
 
  github-release:
    name: github release for tag
    needs: [build-docker]
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: create release
        env:          
          GITHUB_TOKEN: ${{ secrets.GITHUB_TOKEN }}
          NOTES: ${{ github.event.head_commit.message }}
        run: |
          gh release create "${{ github.ref_name }}" --title "${{ github.ref_name }}" --notes "${NOTES}"
          
  move-tags:
    name: move tags
    runs-on: ubuntu-latest
    timeout-minutes: 10
    steps:
      - name: checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: parse semver
        id: semver_parser 
        uses: booxmedialtd/ws-action-parse-semver@v1
        with:
          input_string: ${{ github.ref_name }}
          version_extractor_regex: '\/v(.*)$' 

      - name: move tags
        run: |
          git config user.name "${{ github.actor }}"
          git config user.email "${{ github.actor }}@users.noreply.github.com"

          MAJOR="v${{ steps.semver_parser.outputs.major }}"          
          git tag -fa $MAJOR -m "update ${MAJOR} tag"
          git push origin $MAJOR --force
          
          MINOR="${MAJOR}.${{ steps.semver_parser.outputs.minor }}"
          git tag -fa $MINOR -m "update ${MINOR} tag"
          git push origin $MINOR --force
